T302-betzabefi-guia-ddl
jorgerdc/diplomado-bd-aspirantes pull request #1
Opened 2023-07-04 02:07 UTC by BetzabeFI

Primera versión

2023-09-02 02:35 UTC, BetzabeFI commented on guia-examen/03-ddl/01-ddl.md
> +a una tabla, modificar el tipo de un campo, modificar un trigger, etc.
Ya se realizaron. Gracias

2023-09-02 02:38 UTC, BetzabeFI commented on guia-examen/03-ddl/01-ddl.md
> +se encarga de la modificación de la  estructura de los objetos de la base de datos. Incluye
Por favor se checaría en commit de última actualización. Gracias

2023-09-02 15:51 UTC, LucilaArellano approved these changes

2023-09-02 19:58 UTC, jorgerdc requested changes

2023-09-02 19:58 UTC, jorgerdc commented on guia-examen/03-ddl/01-ddl.md
>  drop table desglose_ventas;
quitar saltos de lìnea entre las instrucciones

2023-09-02 19:58 UTC, jorgerdc commented on guia-examen/03-ddl/01-ddl.md
> +### 3.1.1 Ejemplos sentencia `create`
Perdón Gaby, pero no veo las explicaciones, ¿subirás otro commit ?

2023-09-03 23:40 UTC, BetzabeFI commented on guia-examen/03-ddl/01-ddl.md
>  drop table desglose_ventas;
Eliminados saltos de linea entre las instrucciones. Gracias

2023-09-04 19:11 UTC, jorgerdc approved these changes
ok :)

2023-09-04 19:13 UTC, jorgerdc commented
@LucilaArellano  Un favor, podrías volver a aprobar ? por alguna razó tu aprobación se perdió.  Tal vez fue cuando reorganicé los revisores ya que estaban mal configurados.
Gracias.

2023-09-04 19:52 UTC, LucilaArellano approved these changes

2023-09-07 02:41 UTC, Yatram approved these changes

2023-09-07 15:32 UTC, merged