T305-06-lucilaarellano-dql-joins
jorgerdc/diplomado-bd-aspirantes pull request #10
Opened 2023-08-27 19:33 UTC by LucilaArellano

Favor de revisar

2023-09-02 21:25 UTC, jorgerdc requested changes

2023-09-02 21:25 UTC, jorgerdc commented on guia-examen/06-dql/03-dql-join.md
> +El operador Join se utilizan para recuperar datos de varias tablas. Se realiza un JOIN
utilizan -> utiliza

2023-09-02 21:25 UTC, jorgerdc commented on guia-examen/06-dql/03-dql-join.md
> +obtiene todos los registros de la tabla izuquierda sin importar si tienen correspondencia
typo: izuquierda

2023-09-03 01:50 UTC, LucilaArellano commented on guia-examen/06-dql/03-dql-join.md
> +condición de combinación. Para realizar un `SELF JOIN`, se combinan y devuelve las filas
corregido

2023-09-03 01:50 UTC, LucilaArellano commented on guia-examen/06-dql/03-dql-join.md
> +El operador Join se utilizan para recuperar datos de varias tablas. Se realiza un JOIN
listo

2023-09-03 01:52 UTC, LucilaArellano commented on guia-examen/06-dql/03-dql-join.md
> +condición de combinación. Para realizar un `SELF JOIN`, se combinan y devuelve las filas
Después de la sintaxis esta la aclaración

2023-09-03 01:53 UTC, LucilaArellano commented on guia-examen/06-dql/03-dql-join.md
> +obtiene todos los registros de la tabla izuquierda sin importar si tienen correspondencia
listo

2023-09-03 16:11 UTC, jorgerdc approved these changes
Listo :)

2023-09-06 00:39 UTC, Yatram requested changes

2023-09-06 00:39 UTC, Yatram commented on guia-examen/06-dql/03-dql-join.md
> +En este ejemplo se mostrarán todas los registros de la tabla de `pedido` y solo aquellos
cambiar 'todas los registros' por todos los registros

2023-09-06 00:39 UTC, Yatram commented on guia-examen/06-dql/03-dql-join.md
> +En este ejemplo se mostrarán todas los registros del atributo empleado_id de la tabla de
cambiar 'todas los registros' por todos los registros

2023-09-06 00:39 UTC, Yatram commented on guia-examen/06-dql/03-dql-join.md
> +En este ejemplo se mostrarán todas los registro de los atributos `producto_id` y
cambiar 'todas los registros' por todos los registros

2023-09-06 00:39 UTC, Yatram commented on guia-examen/06-dql/03-dql-join.md
> +En este ejemplo se mostrarán todas los registros de la tabla de `proveedor` y todas los
cambiar 'todas los registros' por todos los registros

2023-09-06 15:32 UTC, LucilaArellano commented on guia-examen/06-dql/03-dql-join.md
> +En este ejemplo se mostrarán todas los registros de la tabla de `pedido` y solo aquellos
listo

2023-09-06 15:32 UTC, LucilaArellano commented on guia-examen/06-dql/03-dql-join.md
> +En este ejemplo se mostrarán todas los registros del atributo empleado_id de la tabla de
listo

2023-09-06 15:33 UTC, LucilaArellano commented on guia-examen/06-dql/03-dql-join.md
> +En este ejemplo se mostrarán todas los registro de los atributos `producto_id` y
listo

2023-09-06 15:35 UTC, LucilaArellano commented on guia-examen/06-dql/03-dql-join.md
> +En este ejemplo se mostrarán todas los registros de la tabla de `proveedor` y todas los
Listo

2023-09-06 15:35 UTC, LucilaArellano commented
Favor de confirmar los cambios

2023-09-06 21:05 UTC, malpgitfi approved these changes

2023-09-07 03:57 UTC, Yatram approved these changes

2023-09-07 18:49 UTC, BetzabeFI approved these changes

2023-09-07 20:02 UTC, jorgerdc commented
Este PR ya puede hacer Merge, pero está bloqueado porque @jorgeacalderon  solicitó cambios. Posiblemente estos cambios ya se hicieron , entonces solo sería cuestión de seleccionar la opción de dismiss review. Solo asegurarse que los cambios solicitados ya hayan sido atendidos. Hacer clic en Changes requested, luego donde aparece el revisor (Jorge) del lado derecho seleccionar  el menú de tres puntos  . . .

2023-09-07 20:55 UTC, jorgeacalderon approved these changes

2023-09-07 21:45 UTC, merged