T308-modelo-relacional
jorgerdc/diplomado-bd-aspirantes pull request #13
Opened 2023-08-29 18:25 UTC by malpgitfi

Favor de revisar

2023-09-02 21:34 UTC, jorgerdc requested changes
Ojo, el archivo no tiene la extensión ".md" , corregir.

2023-09-03 15:40 UTC, malpgitfi commented on guia-examen/02-relacional/01-modRelacional
> +si la ccardinalidad mínima es la misma en ambas entidades dependera el contexto.
corregido

2023-09-03 15:41 UTC, malpgitfi commented on guia-examen/02-relacional/01-modRelacional
> +e) Los atributos derivados se establecen como atributos calculados.
listo :)

2023-09-03 15:41 UTC, malpgitfi commented on guia-examen/02-relacional/01-modRelacional
> +tabla (clave primrari del MER) y en la parte inferior el resto de los atributos:
listo :)

2023-09-03 15:42 UTC, malpgitfi commented
Se corrigió nombre del archivo,

2023-09-03 17:00 UTC, jorgerdc approved these changes
Listo :)

2023-09-05 15:17 UTC, LucilaArellano approved these changes

2023-09-06 00:32 UTC, Yatram requested changes

2023-09-06 00:32 UTC, Yatram commented on guia-examen/02-relacional/01-modRelacional.md
> +En la parte superior del rectangulo, primera parte, se coloca la llave primaria de la
Cambiar 'rectangulo' por rectángulo

2023-09-06 00:32 UTC, Yatram commented on guia-examen/02-relacional/01-modRelacional.md
> +d) Atributo opcional se establace como atributo con valores nulos NULL.
cambiar 'establace' por establece

2023-09-06 00:32 UTC, Yatram commented on guia-examen/02-relacional/01-modRelacional.md
> +Su presentanción en el modelo relacional es:
Cambiar 'presentanción' por representación

2023-09-06 00:36 UTC, malpgitfi commented on guia-examen/02-relacional/01-modRelacional.md
> +Su presentanción en el modelo relacional es:
listo

2023-09-06 00:36 UTC, malpgitfi commented on guia-examen/02-relacional/01-modRelacional.md
> +En la parte superior del rectangulo, primera parte, se coloca la llave primaria de la
listo

2023-09-06 00:41 UTC, Yatram approved these changes

2023-09-06 01:21 UTC, merged