T-315-normalización
jorgerdc/diplomado-bd-aspirantes pull request #15
Opened 2023-08-30 02:23 UTC by malpgitfi

Favor de revisar

2023-09-02 21:39 UTC, jorgerdc commented on guia-examen/02-relacional/03-normalizacion.md
>  * Si un atribto no clave es determiannte de cualquier atributo o atrubtos no clave hay
typos: 
determiannte
atrubutos

2023-09-02 21:39 UTC, jorgerdc commented on guia-examen/02-relacional/03-normalizacion.md
> +
No veo los ejemplos, se agregará otro commit ?

2023-09-02 21:40 UTC, jorgerdc requested changes
No veo los ejemplos

2023-09-03 21:07 UTC, jorgerdc requested changes

2023-09-03 21:07 UTC, jorgerdc commented on guia-examen/02-relacional/03-normalizacion.md
> +Dala la siguiente tabla de datos en la cual está registrada la información de las materias
Dala -> Dada

2023-09-03 21:07 UTC, jorgerdc commented on guia-examen/02-relacional/03-normalizacion.md
> +que cursan alumnos y su calificación, normalizaremos hasta la #FN
#FN -> 3FN ?

2023-09-03 21:07 UTC, jorgerdc commented on guia-examen/02-relacional/03-normalizacion.md
> +  <img src="img/ejemplo.png"/>
No se muestran las imagenes del documento

2023-09-03 21:07 UTC, jorgerdc commented on guia-examen/02-relacional/03-normalizacion.md
> +pacientes tienen apellido materno por lo cual definimos el atributo paciente como
pacientes ? serán estudiantes ? Revisar todo el docto y sustituir por estudiantes

2023-09-03 21:07 UTC, jorgerdc commented on guia-examen/02-relacional/03-normalizacion.md
> +* De acuerdo a las dependencias funcionales determinamos la clave primaria, buscamos que
clave primaria -> llave primaria. En normalización ya el modelo ER se queda en el olvido :p

2023-09-03 21:07 UTC, jorgerdc commented on guia-examen/02-relacional/03-normalizacion.md
> +atributo  o atributos  determinan de manera única a cada uno de los atributos de la tabla
.. determinamos que la llave primaria debe estar formada por un atributo o atributos...

2023-09-03 21:07 UTC, jorgerdc commented on guia-examen/02-relacional/03-normalizacion.md
> +claveunica, clavemateria ->  paterno, materno, nombre, clavealcaldia, alcaldia,
poner la dependencia funcional en un renglòn con tres anticomillas y ponerle sql como lenguaje.

2023-09-03 21:07 UTC, jorgerdc commented on guia-examen/02-relacional/03-normalizacion.md
> +* Determinamos el tipo de pendencias:
pendencias -> dependencias

2023-09-03 21:07 UTC, jorgerdc commented on guia-examen/02-relacional/03-normalizacion.md
> +clavemateria -> clavemateria, nombremateria,  numcreditos
de forma similar, poner anticomillas.

2023-09-03 21:07 UTC, jorgerdc commented on guia-examen/02-relacional/03-normalizacion.md
> +clavealcaldía -> alcaldia
anti comillas

2023-09-03 21:07 UTC, jorgerdc commented on guia-examen/02-relacional/03-normalizacion.md
> +Tabla original MATERIASCURSADAS
MATERIASCURSADAS -> MATERIAS_CURSADAS

2023-09-03 21:07 UTC, jorgerdc commented on guia-examen/02-relacional/03-normalizacion.md
> +
Aquí faltó poner la dependencia funcional, es decir:
claveunica -> paterno, materno, nombre, clavealcaldia

2023-09-03 21:07 UTC, jorgerdc commented on guia-examen/02-relacional/03-normalizacion.md
> +cursos, pero estos campos son independientes. Esto es una dependencia multivalor.
Esta bien el ejemplo, solo que creo que hay que explicar un poco más por què son independientes.
EN realidad son 2 relaciones m:m
curso - estudiante
curso - certificación
En la segunda rrelación se entenderìa cocmo que una certificación requiere de varios cursos
para obtenerse, y un curso puede ser incluido en varias certificaciones, por ejemplo, el curso
de HTML se requiere para 2 certificaciones. Habría que agregar esta relación para que quede
más claro.

Por otro lado, el estudiante toma varios cursos y en un curso hay varrios estudiantes
Y efectivamente, los cursos que toma el estudiante no del todo se asocian al mismo tiempo
con la certificación. Esta un poquito forzado pero funciona..
Aunque, en el modelo antes de pasar a 4FN creo que debería haber 2 FKs que provienen de la tabla
curso, algo asi como estudiante_curso_id, y cert_curso_id. La primera es la que se usa entre la relación estudiante - curso y la segunda entre certificacion y curso. Estas 2 FKs son las que son independientes, y de hecho al ponerlas en la misma tabla deberán ser nulas, ya que para cada registro una tendría sentido y la otra no. Ahì es donde se vería la independencia. Sugiero agregar una tablita pequeña con datos para que quede claro. Para ello se esta empleando la imagen 4fn-ejemplo.png pero tiene errores, , no coincide con los atributos de la tabla ESTUDIANTE_CURRICULA. Sugiero corregir y agregarle la otra fk.

En cuanto a la respuesta propuesta se tienen 2 relaciones m:n

estudiante certificacion
estudiante curso
-Mmmm esto significarìa:
Un estudiante toma varios cursos, un curso la toman varios estudiantees
Una certificaciòn la toman varios estudiantes y un estudiante toma varias certificaciones ?
Mmm la siento rar, forzada.. ¿ no serìa mejor la propuesta que hice ?
Aunque igual la veo algo forzada... jaja creo que el ejemplo no es del todo representativo..

2023-09-04 17:36 UTC, malpgitfi commented on guia-examen/02-relacional/03-normalizacion.md
> +cursos, pero estos campos son independientes. Esto es una dependencia multivalor.
listo, se cambio el texto del ejemplo para dejar claro que son independientes, espero con las imagenes sea todo más claro

2023-09-04 17:36 UTC, malpgitfi commented on guia-examen/02-relacional/03-normalizacion.md
> +Tabla original MATERIASCURSADAS
listo

2023-09-04 17:43 UTC, malpgitfi commented on guia-examen/02-relacional/03-normalizacion.md
> +clavealcaldía -> alcaldia
listo

2023-09-04 17:44 UTC, malpgitfi commented on guia-examen/02-relacional/03-normalizacion.md
> +clavemateria -> clavemateria, nombremateria,  numcreditos
listo

2023-09-04 17:44 UTC, malpgitfi commented on guia-examen/02-relacional/03-normalizacion.md
> +* De acuerdo a las dependencias funcionales determinamos la clave primaria, buscamos que
ok

2023-09-04 17:44 UTC, malpgitfi commented on guia-examen/02-relacional/03-normalizacion.md
> +pacientes tienen apellido materno por lo cual definimos el atributo paciente como
listo

2023-09-04 17:44 UTC, malpgitfi commented on guia-examen/02-relacional/03-normalizacion.md
> +  <img src="img/ejemplo.png"/>
listo

2023-09-04 17:44 UTC, malpgitfi commented on guia-examen/02-relacional/03-normalizacion.md
> +que cursan alumnos y su calificación, normalizaremos hasta la #FN
listo

2023-09-04 17:44 UTC, malpgitfi commented on guia-examen/02-relacional/03-normalizacion.md
> +Dala la siguiente tabla de datos en la cual está registrada la información de las materias
listo

2023-09-04 17:48 UTC, malpgitfi commented on guia-examen/02-relacional/03-normalizacion.md
>  * Si un atribto no clave es determiannte de cualquier atributo o atrubtos no clave hay
listy

2023-09-04 17:49 UTC, malpgitfi commented on guia-examen/02-relacional/03-normalizacion.md
> +entre ellos, se dice que hay dependencias multivalor.
listo

2023-09-04 18:42 UTC, jorgerdc requested changes
Ya casi, solo detalles menores :)

2023-09-04 18:42 UTC, jorgerdc commented on guia-examen/02-relacional/03-normalizacion.md
quitar línea 76, salto de línea innecesario

2023-09-04 18:42 UTC, jorgerdc commented on guia-examen/02-relacional/03-normalizacion.md
quitar línea 80, salto de línea innecesario

2023-09-04 18:42 UTC, jorgerdc commented on guia-examen/02-relacional/03-normalizacion.md
> +* De acuerdo a las dependencias funcionales determinamos la llave primaria, buscamos que
.. buscamos al atributo o atributos que determinan ..

2023-09-04 18:42 UTC, jorgerdc commented on guia-examen/02-relacional/03-normalizacion.md
>  Las llaves primarias compuestas generan dependencias parciales
Sugiero mover esta linea a  justo abajo de la línea 97 para que no se confunda con las transitivas

2023-09-04 18:42 UTC, jorgerdc commented on guia-examen/02-relacional/03-normalizacion.md
>  determina a otro atributo que tampoco es clave
* Es dependencia transitiva ya que un atributo que no es parte de la llave primaria
determina a otro atributo que tampoco es clave	determina otro atributo que tampoco forma parte de la llave primaria.

2023-09-04 18:42 UTC, jorgerdc commented on guia-examen/02-relacional/03-normalizacion.md
>  se establecen como llaves foráneas fk
En lugar de  los incisos a) b) c)  continuar el uso de viñetas (*) ya que  los incisos MD no los reconoce como listas y salen en un solo renglón

2023-09-04 18:42 UTC, jorgerdc commented on guia-examen/02-relacional/03-normalizacion.md
Mismo caso, emplear viñetas en lugar de a) b)

2023-09-04 18:42 UTC, jorgerdc commented on guia-examen/02-relacional/03-normalizacion.md
> +certificaciones.Las  certificaciones no tienen nada que ver con los cursos.
... considerar las siguientes reglas ne de negocio:
* Un curso lo toman varios estudiantes, un estudiante puede tomar varios cursos de preparación.
* Una certificación puede ser adquirida por varios estudiantes,  un estudiante puede obtener varias certificaciones.
* Los cursos de preparación que se ofrecen no se asocian de forma directa con una certificación, son cursos genéricos que contribuyen con el aprendizaje del estudiante.

2023-09-04 18:42 UTC, jorgerdc commented on guia-examen/02-relacional/03-normalizacion.md
Las últimas 2 imágenes no se ven.

2023-09-04 18:45 UTC, jorgerdc requested changes
Revisar imágenes, no se ven.

2023-09-04 18:45 UTC, jorgerdc commented on guia-examen/02-relacional/03-normalizacion.md
> +<p align="center"><img src="img/4fn-final.jpg"/></p>
Las imágenes siguen teniendo problemas

2023-09-04 18:51 UTC, malpgitfi commented on guia-examen/02-relacional/03-normalizacion.md
> +certificaciones.Las  certificaciones no tienen nada que ver con los cursos.
listo

2023-09-04 18:52 UTC, malpgitfi commented on guia-examen/02-relacional/03-normalizacion.md
listo

2023-09-04 18:53 UTC, malpgitfi commented on guia-examen/02-relacional/03-normalizacion.md
>  se establecen como llaves foráneas fk
listo

2023-09-04 18:54 UTC, malpgitfi commented on guia-examen/02-relacional/03-normalizacion.md
>  determina a otro atributo que tampoco es clave
listo

2023-09-04 18:55 UTC, malpgitfi commented on guia-examen/02-relacional/03-normalizacion.md
>  Las llaves primarias compuestas generan dependencias parciales
listo

2023-09-04 18:56 UTC, malpgitfi commented on guia-examen/02-relacional/03-normalizacion.md
> +* De acuerdo a las dependencias funcionales determinamos la llave primaria, buscamos que
listo

2023-09-04 18:57 UTC, malpgitfi commented on guia-examen/02-relacional/03-normalizacion.md
listo

2023-09-04 18:57 UTC, malpgitfi commented on guia-examen/02-relacional/03-normalizacion.md
listo

2023-09-05 15:20 UTC, LucilaArellano approved these changes

2023-09-05 20:07 UTC, jorgerdc approved these changes

2023-09-06 00:20 UTC, Yatram approved these changes

2023-09-06 16:00 UTC, LucilaArellano commented on guia-examen/02-relacional/03-normalizacion.md
> +* Determinamos el tipo de pendencias:
realizado

2023-09-06 16:03 UTC, LucilaArellano commented on guia-examen/02-relacional/03-normalizacion.md
> +claveunica, clavemateria ->  paterno, materno, nombre, clavealcaldia, alcaldia,
realizado

2023-09-06 17:11 UTC, malpgitfi commented on guia-examen/02-relacional/03-normalizacion.md
yo si las veo, podrias revisar el ultimo commit por favor

2023-09-06 21:06 UTC, merged