T310-jorgerdc-guia-linux
jorgerdc/diplomado-bd-aspirantes pull request #16
Opened 2023-08-30 04:41 UTC by jorgerdc

Se agrega material   8. Fundamentos de Linux

2023-09-02 16:43 UTC, LucilaArellano requested changes

2023-09-02 16:43 UTC, LucilaArellano commented on guia-examen/08-fundamentos-linux/03-comandos-basicos.md
> +con expresiones regulares. Se puede usar para filtrar las lineas de un archivo de disco o
acentuar líneas

2023-09-02 16:43 UTC, LucilaArellano commented on guia-examen/08-fundamentos-linux/02-sistema-archivos.md
> +directorio, al cual apunta. Cuando usamos un enlace simbólico en un comando, este en
acentuar éste

2023-09-02 16:43 UTC, LucilaArellano commented on guia-examen/08-fundamentos-linux/03-comandos-basicos.md
> +* `-n`: Indica el número de linea donde ha encontrado el patrón
acentuar línea

2023-09-02 16:43 UTC, LucilaArellano commented on guia-examen/08-fundamentos-linux/03-comandos-basicos.md
> +* `-c`: Muestra la cantidad de lineas que cumplen con el patrón
acentuar líneas

2023-09-02 16:43 UTC, LucilaArellano commented on guia-examen/08-fundamentos-linux/03-comandos-basicos.md
> +selecciona del fichero sources.list las lineas que NO tienen el texto deb-src
acentuar líneas

2023-09-02 16:43 UTC, LucilaArellano commented on guia-examen/08-fundamentos-linux/03-comandos-basicos.md
> +busca las lineas que contengan la palabra ssh dentro del historial de comandos.
acentuar líneas

2023-09-02 21:42 UTC, jorgerdc commented on guia-examen/08-fundamentos-linux/01-conceptos-basicos.md
> +La filosofía de Unix esta basada en los principios de  minimalismo y modularidad: hacer
resuelto

2023-09-02 21:42 UTC, jorgerdc commented on guia-examen/08-fundamentos-linux/01-conceptos-basicos.md
> +A principios de los 90s, Linus Torvalds comenzo con la escritura de un sistema operativo
listo

2023-09-02 21:43 UTC, jorgerdc commented on guia-examen/08-fundamentos-linux/01-conceptos-basicos.md
> +Es importante mencionar que prácticamente todo lo que se escribe el Linux es
listo

2023-09-02 21:44 UTC, jorgerdc commented on guia-examen/08-fundamentos-linux/01-conceptos-basicos.md
> +que el usuario inicia sesión. Entro otras cosas, este entorno contiene los valores
listo

2023-09-02 21:44 UTC, jorgerdc commented on guia-examen/08-fundamentos-linux/01-conceptos-basicos.md
> +* `SHELL`: Describe el interprete shell que se empleará para procesar comandos.
listo

2023-09-02 21:45 UTC, jorgerdc commented on guia-examen/08-fundamentos-linux/02-sistema-archivos.md
> +3. Archivos especiales: on los archivos que representan a los dispositivos de
listo

2023-09-02 21:46 UTC, jorgerdc commented on guia-examen/08-fundamentos-linux/02-sistema-archivos.md
> +El comando `mv` sirve para mover archivo y directorios a otros directorios y para
listo

2023-09-02 21:47 UTC, jorgerdc commented on guia-examen/08-fundamentos-linux/03-comandos-basicos.md
> +consultar  el manual del comando empleando la instricción `man find`
listo

2023-09-02 21:48 UTC, jorgerdc commented on guia-examen/08-fundamentos-linux/03-comandos-basicos.md
> +El comando `grep` selecciona las lineas de texto que contengan un patrón que podemos definir
listo

2023-09-02 21:49 UTC, jorgerdc commented on guia-examen/08-fundamentos-linux/04-permisos.md
> +contraseña del usuario, aparece una `x`, el sistema almacena las contraseañas en
listo

2023-09-02 21:51 UTC, jorgerdc commented on guia-examen/08-fundamentos-linux/04-permisos.md
> +* a nivel del propietario dueño del archivo.
corregido

2023-09-02 21:51 UTC, jorgerdc commented on guia-examen/08-fundamentos-linux/03-comandos-basicos.md
> +con expresiones regulares. Se puede usar para filtrar las lineas de un archivo de disco o
listo

2023-09-02 21:54 UTC, jorgerdc commented on guia-examen/08-fundamentos-linux/02-sistema-archivos.md
> +directorio, al cual apunta. Cuando usamos un enlace simbólico en un comando, este en
listo

2023-09-02 21:55 UTC, jorgerdc commented on guia-examen/08-fundamentos-linux/03-comandos-basicos.md
> +* `-n`: Indica el número de linea donde ha encontrado el patrón
listo

2023-09-02 21:56 UTC, jorgerdc commented on guia-examen/08-fundamentos-linux/03-comandos-basicos.md
> +* `-c`: Muestra la cantidad de lineas que cumplen con el patrón
listo

2023-09-02 21:58 UTC, jorgerdc commented on guia-examen/08-fundamentos-linux/03-comandos-basicos.md
> +selecciona del fichero sources.list las lineas que NO tienen el texto deb-src
listo

2023-09-02 21:58 UTC, jorgerdc commented on guia-examen/08-fundamentos-linux/03-comandos-basicos.md
> +busca las lineas que contengan la palabra ssh dentro del historial de comandos.
listo

2023-09-03 02:14 UTC, LucilaArellano requested changes

2023-09-03 16:14 UTC, jorgerdc commented on guia-examen/08-fundamentos-linux/01-conceptos-basicos.md
> +
yo la veo bien. Tal vez por el tiempo, podríamos dejarlo como mejora.  No les hace daño leer un poco más :p

2023-09-04 02:17 UTC, jorgeacalderon approved these changes

2023-09-05 00:12 UTC, Yatram approved these changes

2023-09-05 19:45 UTC, LucilaArellano approved these changes

2023-09-05 19:45 UTC, LucilaArellano approved these changes

2023-09-05 20:09 UTC, merged