T303-lucilaarellano-dql-algebra
jorgerdc/diplomado-bd-aspirantes pull request #2
Opened 2023-08-02 01:56 UTC by LucilaArellano

Favor de revisar

2023-09-02 20:00 UTC, jorgerdc commented on guia-examen/06-dql/01-algebra.md
> +  de atributos y el dominio del atributo i-ésimo de cada relación debe coincidir.
ok

2023-09-02 20:29 UTC, jorgerdc requested changes

2023-09-02 20:29 UTC, jorgerdc commented on guia-examen/06-dql/01-algebra.md
>  <p align ="center"\><img src=img/seleccion.png width="400"></p>
Esta imagen no se ve. Tal vez no existe ? o tiene un nombre diferente ? O tal vez le faltan las comillas al atributo src.  Es decir src="img/seleccion.png"

2023-09-02 20:29 UTC, jorgerdc commented on guia-examen/06-dql/01-algebra.md
>    <p align="center"\><img src=img/proyeccion.png width="400"></p>
checar todas las imágenes del documento, no se ven.

2023-09-02 20:29 UTC, jorgerdc commented on guia-examen/06-dql/01-algebra.md
>    * Propios de Bases de Datos y de conjuntos.
En la nueva versión solo se habla de los  operadores Báśicos y derivados, lo cual es correcto.  Entonces sugiero que aquí se modiique a lo siguiente:
* Básicos
* Derivados

2023-09-03 01:00 UTC, LucilaArellano commented on guia-examen/06-dql/01-algebra.md
>  <p align ="center"\><img src=img/seleccion.png width="400"></p>
Se cambio la figura

2023-09-03 01:00 UTC, LucilaArellano commented on guia-examen/06-dql/01-algebra.md
>    * Propios de Bases de Datos y de conjuntos.
listo

2023-09-03 01:01 UTC, LucilaArellano commented on guia-examen/06-dql/01-algebra.md
>    <p align="center"\><img src=img/proyeccion.png width="400"></p>
Revisado

2023-09-03 01:48 UTC, jorgerdc approved these changes
super!

2023-09-03 21:35 UTC, jorgeacalderon commented on guia-examen/06-dql/01-algebra.md
> +* Sus operadores estan diseñados para realizar el acceso a datos como parte del
cambiar "estan" por "están"

2023-09-03 21:36 UTC, jorgeacalderon commented on guia-examen/06-dql/01-algebra.md
> +* Las operaciones de álgebra relacional actuán sobre relaciones generando como resultado
cambiar "actuán" por "actúan"

2023-09-03 21:36 UTC, jorgeacalderon commented on guia-examen/06-dql/01-algebra.md
> +  horizontales de cualquer par de relaciones. Son uniones horizontales porque a partir de
cambiar "cualquer " por "cualquier"

2023-09-03 21:37 UTC, jorgeacalderon commented on guia-examen/06-dql/01-algebra.md
> +  dos relaciones se obtiene una sola, cuyas columnas es la unión de las columnas de las
cambiar "es la" por "son la"

2023-09-03 21:37 UTC, jorgeacalderon commented on guia-examen/06-dql/01-algebra.md
> +  Combina tuplas de cualquieras dos (o más) relaciones, hace la combinación de todos con
cambiar "cualquieras " por "cualesquieras "

2023-09-04 15:28 UTC, LucilaArellano commented on guia-examen/06-dql/01-algebra.md
> +* Sus operadores estan diseñados para realizar el acceso a datos como parte del
listo

2023-09-04 15:29 UTC, LucilaArellano commented on guia-examen/06-dql/01-algebra.md
> +* Las operaciones de álgebra relacional actuán sobre relaciones generando como resultado
listo

2023-09-04 15:30 UTC, LucilaArellano commented on guia-examen/06-dql/01-algebra.md
> +  dos relaciones se obtiene una sola, cuyas columnas es la unión de las columnas de las
listo

2023-09-04 15:31 UTC, LucilaArellano commented on guia-examen/06-dql/01-algebra.md
> +  Combina tuplas de cualquieras dos (o más) relaciones, hace la combinación de todos con
listo

2023-09-05 22:03 UTC, jorgeacalderon approved these changes

2023-09-06 17:04 UTC, malpgitfi approved these changes

2023-09-06 19:33 UTC, merged