T304-COMMIT PARA PRIMER REVISION
jorgerdc/diplomado-bd-aspirantes pull request #3
Opened 2023-08-14 22:54 UTC by malpgitfi

Para primer revisión

2023-09-02 16:47 UTC, LucilaArellano commented on guia-examen/01-mer/01-mer.md
> +Una entidad es cualquier objeto real o abstracto con existencia propia acerca del cual queremos almacenar información en la base de datos. Las entidades se representan mediante un rectángulo con el n
Sugiero no quitar la regla y en los ejemplos respetarla

2023-09-02 17:09 UTC, LucilaArellano commented on guia-examen/01-mer/01-mer.md
> +* Multivalor, almacena múltiples valores para el mismo atributo, un ejemplo es los números de teléfonos para un alumno, se utilizan círculos concentricos para representarlo.
círculos -> elipses

2023-09-02 18:30 UTC, malpgitfi commented on guia-examen/01-mer/01-mer.md
> +
Más abajo se describen las entidades débiles

2023-09-02 18:32 UTC, malpgitfi commented on guia-examen/01-mer/01-mer.md
> +Un atributo es una característica o propiedad que describe una entidad. Por ejemplo, la entidad alumno puede describirse mediante el nombre, fecha de nacimiento, edad, domicilio y número de cuenta. A
realizado

2023-09-02 18:32 UTC, malpgitfi commented on guia-examen/01-mer/01-mer.md
> +* Multivalor, almacena múltiples valores para el mismo atributo, un ejemplo es los números de teléfonos para un alumno, se utilizan círculos concentricos para representarlo.
realizado

2023-09-02 18:34 UTC, malpgitfi commented on guia-examen/01-mer/01-mer.md
> +* Discriminante, las entidades débiles dependen de la entidad fuerte para ser identificadas, por lo que tienen un atributo que junto con el atributo clave primaria de su entidad fuerte identifican de
realizado

2023-09-02 18:34 UTC, malpgitfi commented on guia-examen/01-mer/01-mer.md
> +* Clave candidata, en ocasiones una entidad puede tener más de un atributo que puede identificar de manera única a cada ejemplar de la entidad, estos atributos se llaman claves candidatas por ejemplo
realizado

2023-09-02 18:35 UTC, malpgitfi commented on guia-examen/01-mer/01-mer.md
> +* Grado, es el número de entidades que participan en una relación, una relación de grado 2 se refiere a la vinculación entre 2 entidades. Las relaciones de grado 1 son relaciones entre la misma entid
realizado

2023-09-02 18:35 UTC, malpgitfi commented on guia-examen/01-mer/01-mer.md
> +* Se almacenará el nombre, numero del documento nacional de identidad, el domicilio (calle, numero, alcaldía), el sueldo, el sexo, la fecha de nacimiento de cada empleado y la clave que lo identifica
se hizo el cambio

2023-09-02 18:36 UTC, malpgitfi commented on guia-examen/01-mer/01-mer.md
> +El primer paso en el diseño de una base de datos es la recopilación de requisitos, estos requisitos se detallan en un documento. El siguiente paso es realizar un diseño conceptual de la base de datos
agregado

2023-09-02 18:36 UTC, malpgitfi commented on guia-examen/01-mer/01-mer.md
> +El modelo conceptual es una descripción concisa de los requisitos de datos por parte de los usuarios, que nos permite representar la realidad en una forma dirigida al almacenamiento de los datos, par
agregado

2023-09-02 18:36 UTC, malpgitfi commented on guia-examen/01-mer/01-mer.md
> +En el diseño conceptual se crea una representación gráfica conocida como modelo entidad relación muy conocido como MER propuesta por Peter Chen en 1976. A continuación se detallan los elementos del M
se hizo el cambio

2023-09-02 18:37 UTC, malpgitfi commented on guia-examen/01-mer/01-mer.md
> +Una entidad es cualquier objeto real o abstracto con existencia propia acerca del cual queremos almacenar información en la base de datos. Las entidades se representan mediante un rectángulo con el n
se dejo en MAYUSCULA

2023-09-02 18:37 UTC, malpgitfi commented on guia-examen/01-mer/01-mer.md
> +Existen entidades llamadas débiles, cuya existencia depende de que exista otra entidad denominada fuerte. Las entidades débiles se representan con doble rectángulo.
se corrigió en todo el documento

2023-09-02 18:37 UTC, malpgitfi commented on guia-examen/01-mer/01-mer.md
> +* Simple, atributo que no puede subdividirse como la edad, un atributo se representa con un circulo con su nombre dentro del mismo y se une a la entidad que representa mediante una línea.
listo

2023-09-02 18:38 UTC, malpgitfi commented on guia-examen/01-mer/01-mer.md
> +* Multivalor, almacena múltiples valores para el mismo atributo, un ejemplo es los números de teléfonos para un alumno, se utilizan círculos concentricos para representarlo.
corregido

2023-09-02 18:39 UTC, malpgitfi commented on guia-examen/01-mer/01-mer.md
> +* Atributo clave, una restricción importante de las entidades es la clave o restricción de unicidad. Una entidad siempre debe tener un atributo o atributos cuyos valores son distintos para cada ejemp
se hizo el cambio

2023-09-02 18:39 UTC, malpgitfi commented on guia-examen/01-mer/01-mer.md
> +* Discriminante, las entidades débiles dependen de la entidad fuerte para ser identificadas, por lo que tienen un atributo que junto con el atributo clave primaria de su entidad fuerte identifican de
se colocó clave débil o discriminante

2023-09-02 18:39 UTC, malpgitfi commented on guia-examen/01-mer/01-mer.md
> +A continuación, se presentan los requisitos de una EMPRESA que requiere dar seguimiento de los
listo

2023-09-02 20:59 UTC, jorgerdc requested changes

2023-09-02 20:59 UTC, jorgerdc commented on guia-examen/01-mer/01-mer.md
> +los usuarios.
Este párrafo prácticamente dice lo mismo respecto al siguiente. Sugiero quitarlo, o compararlo con el siguiente párrafo y fuisionarlos.

2023-09-02 20:59 UTC, jorgerdc commented on guia-examen/01-mer/01-mer.md
> +ingenieria de software, estructiras discretas, bases de datos).
No me queda clara la definición de dominio,  creo que esta definición está media complicada.  Según yo, el dominio de un atributo A, se define como una lista de todos los posibles valores que puede adquirir el atributo A.  Me confundí con esto del predicado, creo que haría falta un poco más de explicación.

2023-09-02 20:59 UTC, jorgerdc commented on guia-examen/01-mer/01-mer.md
> +valor aplicable para un atributo, por ejemplo, número de hijos para un alumno, para
.. para un alumno. Para estos casos ...

2023-09-02 20:59 UTC, jorgerdc commented on guia-examen/01-mer/01-mer.md
> +* Atributo clave, Cada entidad debe definir un atributo clave empleado para
Atributo clave o clave principal

2023-09-02 20:59 UTC, jorgerdc commented on guia-examen/01-mer/01-mer.md
> +* Clave débil, las entidades débiles dependen de la entidad fuerte para ser identificadas, por lo que tienen un atributo que junto con el atributo clave primaria
..identificadas. Su clave principal será compuesta, es decir, estará formada por la clave principal de la entidad fuerte así como de la clave principal de la entidad débil.

Sugiero no poner tèrminos como   clave "primaria", ya que  la palabra "Primaria" o "llave" son conceptos del modelo relacional. En  el modelo E/R solo existen las claves.

2023-09-02 20:59 UTC, jorgerdc commented on guia-examen/01-mer/01-mer.md
> +a este atributo se le llama clave débil o discriminante y se representa subrayando el nombre del atributo con una línea discontinua.
Sugiero quitar la palabra discriminante.

2023-09-02 20:59 UTC, jorgerdc commented on guia-examen/01-mer/01-mer.md
> +ejemplar de una entidad. Los tipos son uno a uno (1:1), uno a muchos (1,M) y muchos a muchos (M:M)
* Tipos de relaciones:  Número de ejemplares de una entidad  asociados con un ejemplear o instancia de la otra entidad. Existen 3 tipos:
  * Uno a Uno (1:1)
  * Uno a muchos (1:m)
  *  Muchos a muchos (m:m)

2023-09-02 20:59 UTC, jorgerdc commented on guia-examen/01-mer/01-mer.md
> +* Cardinalidad, se define como el número máximo y mínimo de ejemplares de una entidad
mínimo y máximo

2023-09-02 20:59 UTC, jorgerdc commented on guia-examen/01-mer/01-mer.md
> +que puede estar relacionada con un ejemplar de la otra entidad. Los valores que pueden tomar son (0,1), (1,1), (0,m) o (1,m), donde m significa muchos ejemplares.
relacionados

2023-09-02 21:00 UTC, jorgerdc requested changes

2023-09-02 21:00 UTC, jorgerdc commented on guia-examen/01-mer/01-mer.md
> +colonia y alcaldía. Gráficamente se crea el atributo y se unen a él mediante una línea los
número, colonia

2023-09-02 21:04 UTC, jorgerdc commented on guia-examen/01-mer/01-mer.md
> +<p align="center"\><img src="img/entidad.png"\></p>
¿ por qué se cambió la diagonal? estaba bien, debe ser:
` <p align="center"><img src="img/entidad.png"/></p>`

2023-09-02 21:04 UTC, jorgerdc commented on guia-examen/01-mer/01-mer.md
> +<p align="center"\><img src="img/entidad-debil.png"\></p>
Mismo caso que el comentario anterior, revisar todo el docuento

2023-09-02 23:59 UTC, LucilaArellano commented on guia-examen/01-mer/01-mer.md
> +
Pero no se menciona la simbología para la relación que asocia a la entidad débil con la fuerte

2023-09-03 14:23 UTC, malpgitfi commented on guia-examen/01-mer/01-mer.md
> +<p align="center"\><img src="img/entidad.png"\></p>
las cambie porque me marcaba error (línea en amarillo), pero ya las regresé como estaban :)

2023-09-03 14:23 UTC, malpgitfi commented on guia-examen/01-mer/01-mer.md
> +<p align="center"\><img src="img/entidad-debil.png"\></p>
listo

2023-09-03 14:31 UTC, malpgitfi commented on guia-examen/01-mer/01-mer.md
> +colonia y alcaldía. Gráficamente se crea el atributo y se unen a él mediante una línea los
listo

2023-09-03 14:32 UTC, malpgitfi commented on guia-examen/01-mer/01-mer.md
> +que puede estar relacionada con un ejemplar de la otra entidad. Los valores que pueden tomar son (0,1), (1,1), (0,m) o (1,m), donde m significa muchos ejemplares.
corregido

2023-09-03 14:38 UTC, malpgitfi commented on guia-examen/01-mer/01-mer.md
> +* Cardinalidad, se define como el número máximo y mínimo de ejemplares de una entidad
corregido

2023-09-03 14:41 UTC, malpgitfi commented on guia-examen/01-mer/01-mer.md
> +ejemplar de una entidad. Los tipos son uno a uno (1:1), uno a muchos (1,M) y muchos a muchos (M:M)
listo

2023-09-03 14:42 UTC, malpgitfi commented on guia-examen/01-mer/01-mer.md
> +a este atributo se le llama clave débil o discriminante y se representa subrayando el nombre del atributo con una línea discontinua.
Paty comentó que no se quitará, por eso deje las dos, considero que colocando "clave débil o discriminante" se aclara

2023-09-03 14:50 UTC, malpgitfi commented on guia-examen/01-mer/01-mer.md
> +* Clave débil, las entidades débiles dependen de la entidad fuerte para ser identificadas, por lo que tienen un atributo que junto con el atributo clave primaria
listo

2023-09-03 14:50 UTC, malpgitfi commented on guia-examen/01-mer/01-mer.md
> +* Atributo clave, Cada entidad debe definir un atributo clave empleado para
listo

2023-09-03 14:53 UTC, malpgitfi commented on guia-examen/01-mer/01-mer.md
> +valor aplicable para un atributo, por ejemplo, número de hijos para un alumno, para
listo

2023-09-03 15:02 UTC, malpgitfi commented on guia-examen/01-mer/01-mer.md
> +ingenieria de software, estructiras discretas, bases de datos).
se corrigió, espero haber sido más clara

2023-09-03 15:03 UTC, malpgitfi commented on guia-examen/01-mer/01-mer.md
> +los usuarios.
listo

2023-09-03 15:12 UTC, malpgitfi commented on guia-examen/01-mer/01-mer.md
> +
si Paty perdón, ya lo agregué

2023-09-03 16:29 UTC, jorgerdc commented on guia-examen/01-mer/01-mer.md
> +a este atributo se le llama clave débil o discriminante y se representa subrayando el nombre del atributo con una línea discontinua.
ok

2023-09-03 16:32 UTC, jorgerdc commented on guia-examen/01-mer/01-mer.md
> +<p align="center"\><img src="img/entidad.png"\></p>
oooh ya. La línea en amrillo indica que no se debe poner html en los archivos MD. Sin embargo,  el el archivo `.markdownlint.json`  agregamos una excepción para que no nos marque ese warning. Debido a que este archivo aún no ha hecho merge, nos marca este detalle.  Este warning va a desaparecer cuando hagamos merge.

2023-09-03 16:43 UTC, jorgerdc commented on guia-examen/01-mer/01-mer.md
> +ingenieria de software, estructiras discretas, bases de datos).
Esta bien, solo que ahora el concepto del "predicado" como que y no le encuentro su uso. Entiendo que el predicado es una condición,  pero ¿cómo se aplica este predicado al concepto de dominio?,  Mmm tal vez se refiere a que para cada registro se aplica el predicado P para seleccionar un elemento de la lista del dominio ?

2023-09-03 16:53 UTC, jorgerdc requested changes
Ya casi, solo un par de observaciones :)

2023-09-03 16:53 UTC, jorgerdc commented on guia-examen/01-mer/01-mer.md
> +Muchos a muchos (m:m)
Agregar un asterisco al principio para hacer una lista ya que así como está los  3 renglónes aparecen en una sola línea

2023-09-05 23:57 UTC, malpgitfi commented on guia-examen/01-mer/01-mer.md
> +Muchos a muchos (m:m)
listo

2023-09-06 19:40 UTC, jorgerdc requested changes
Solo una observación más

2023-09-06 19:40 UTC, jorgerdc commented on guia-examen/01-mer/01-mer.md
> +<p align="center"><img src="img/dominio.png"/></p>
Sugiero quitar la parte del predicado, incluso creo que se podría quitar la imagen. La definición nunca hace referencia al predicado, por  lo que genera confusión.  Es mejor omitir el uso de ese predicado, en su defecto, checar la fuente para ver cual es la idea de este predicado.

2023-09-06 20:59 UTC, malpgitfi commented on guia-examen/01-mer/01-mer.md
> +Un ejemplo de entidad débil sería ejemplar que es débil respecto a la entidad libro, ejemplar es débil porque su existencia depende de la entidad libro.
listo

2023-09-06 21:01 UTC, malpgitfi commented on guia-examen/01-mer/01-mer.md
> +<p align="center"><img src="img/dominio.png"/></p>
listo

2023-09-07 02:09 UTC, jorgerdc approved these changes

2023-09-07 02:10 UTC, jorgerdc commented
Listo!

2023-09-07 02:25 UTC, BetzabeFI approved these changes

2023-09-07 15:30 UTC, merged