T309-jorgerdc-guia-pl-sql
jorgerdc/diplomado-bd-aspirantes pull request #5
Opened 2023-08-20 21:58 UTC by jorgerdc

Material para la guía de estudio del diplomado: Introducción a la programaciòn PL/SQL
Favor de revisar.

2023-09-02 17:34 UTC, LucilaArellano requested changes

2023-09-02 17:34 UTC, LucilaArellano commented on guia-examen/07-programacion-plsql/02-triggers.md
> +trigger se asocia a la tabla (no a los datos). En esta categoría un trigger pueden ser
cambiar pueden por puede

2023-09-02 21:11 UTC, jorgerdc commented on guia-examen/07-programacion-plsql/02-triggers.md
> +trigger se asocia a la tabla (no a los datos). En esta categoría un trigger pueden ser
Listo

2023-09-03 21:42 UTC, jorgeacalderon commented on guia-examen/07-programacion-plsql/02-triggers.md
> +modificando o eliminando. Sus valores dependen de tipo de operación DML:
cambiar "de tipo" por "del tipo"

2023-09-04 18:54 UTC, jorgerdc commented on guia-examen/07-programacion-plsql/02-triggers.md
> +modificando o eliminando. Sus valores dependen de tipo de operación DML:
listo!

2023-09-05 19:36 UTC, LucilaArellano approved these changes

2023-09-05 22:04 UTC, jorgeacalderon approved these changes

2023-09-07 02:32 UTC, BetzabeFI approved these changes

2023-09-07 02:36 UTC, merged