T310-ricardorr-ciencias-basicas
jorgerdc/diplomado-bd-aspirantes pull request #6
Opened 2023-08-23 07:29 UTC by Yatram

Se crean tres de los 4 temas de la guía para la parte de analítica. De los cuales son Algebra, Calculo Diferencial y ED.

2023-09-02 19:12 UTC, Yatram commented on guia-examen/10-ciencias-basicas/00-Temario-Ciencia de Datos.md
> +    3.3 Ecuaciones Diferenciales Lineales no homogeneas.
Listo

2023-09-02 21:14 UTC, jorgerdc requested changes
Las imágenes siguen sin visualizarse correctamente :(

2023-09-03 21:34 UTC, jorgerdc requested changes
Las imágenes no se muestran correctamente.

2023-09-05 19:37 UTC, LucilaArellano approved these changes

2023-09-05 22:01 UTC, jorgeacalderon approved these changes

2023-09-06 19:16 UTC, jorgerdc requested changes
Corregir el nomre de la imagen "Sin título.png"  Puede que no funcione por el acento y el espacio

2023-09-06 19:27 UTC, jorgerdc approved these changes
Hay un archivo que se llama "Sin título.png" Sospecho que no se usa, por loq ue debe elimianrse. Corregir, ya no se requiere otra revisión, este PR ya puede hacer merge

2023-09-07 22:45 UTC, jorgerdc commented
Este PR se cierra, su contenido fue integrado en otro.

2023-09-07 22:45 UTC, closed without merging