T311-betzabe-04-dml
jorgerdc/diplomado-bd-aspirantes pull request #8
Opened 2023-08-27 18:48 UTC by BetzabeFI

Version 1 4-DML

2023-09-02 02:44 UTC, BetzabeFI commented on guia-examen/04-dml/04-dml.md
> +    `select`, esta sentencia se utiliza para realizar
Ya quite lineas. Gracias

2023-09-02 21:18 UTC, jorgerdc requested changes
El problema de los espacios no se ha resuelto. Se siguen mostrando  mal las secciones de código. Sugiero  abrir la interfaz gráfica  en  GitHub para ver los errores.

2023-09-02 21:18 UTC, jorgerdc commented on guia-examen/04-dml/04-dml.md
> +    ```sql
En la línea 22 no se han quitado los espacios.

2023-09-04 00:00 UTC, BetzabeFI commented on guia-examen/04-dml/04-dml.md
> +    ```sql
En línea 22 eliminado espacio y también el cierre. Gracias

2023-09-04 00:04 UTC, BetzabeFI commented on guia-examen/04-dml/04-dml.md
> +rollback;
Corrobore que se explico commit y rollback, y tablas en singular. Gracias

2023-09-04 02:10 UTC, jorgeacalderon requested changes
Siguen existiendo problemas al mostrar secciones sql

2023-09-04 19:41 UTC, jorgerdc requested changes
Por favor, corregir los ejemplos. No se visualizan correctamente.

2023-09-04 19:41 UTC, jorgerdc commented on guia-examen/04-dml/04-dml.md
>      ```sql
Los ejemplos a partir de la sentencia insert siguen sin mostrarse bien.

2023-09-05 19:38 UTC, LucilaArellano approved these changes

2023-09-05 22:05 UTC, jorgeacalderon approved these changes

2023-09-07 02:19 UTC, BetzabeFI commented on guia-examen/04-dml/04-dml.md
>      ```sql
Ya no tiene espacios. Gracias

2023-09-07 02:34 UTC, jorgerdc approved these changes

2023-09-07 02:38 UTC, merged