T312-betzabe-05-dtl
jorgerdc/diplomado-bd-aspirantes pull request #9
Opened 2023-08-27 19:18 UTC by BetzabeFI

Primera versión dtl

2023-09-02 00:48 UTC, BetzabeFI commented on guia-examen/05-dtl/05-dtl.md
> +En Oracle si se ejecuta un conjunto de operaciones y si una de ellas falla se aborta
Muy bien eleminado En Oracle.  Gracias

2023-09-02 01:03 UTC, BetzabeFI commented on guia-examen/05-dtl/05-dtl.md
> +
Incluí breve explicación. Gracias

2023-09-02 01:04 UTC, BetzabeFI commented on guia-examen/05-dtl/05-dtl.md
> +liberando los renglones bloqueados.
Realizado el cambio.Gracias

2023-09-02 01:07 UTC, BetzabeFI commented on guia-examen/05-dtl/05-dtl.md
> +Sólo después de que se ejecute commit tendremos acceso a los datos modificados.
Muy bien, entre comillas. Gracias

2023-09-02 01:09 UTC, BetzabeFI commented on guia-examen/05-dtl/05-dtl.md
> +haber producido en la misma, liberando los renglones bloqueados. Se utiliza especialmente
Cambiado, Gracias

2023-09-02 01:10 UTC, BetzabeFI commented on guia-examen/05-dtl/05-dtl.md
> +cuando no se puede concluir una transacción porque se han levantado excepciones.
Cambio realizado. Gracias

2023-09-02 01:12 UTC, BetzabeFI commented on guia-examen/05-dtl/05-dtl.md
> +Se utiliza para poner marcas o puntos de salvaguarda al procesar transacciones. Se utiliza
Cambio realizado. Gracias

2023-09-02 01:13 UTC, BetzabeFI commented on guia-examen/05-dtl/05-dtl.md
> +junto con rollback permitiendo deshacer cambios hasta los `savepoint`.
Cambio realizado. Gracias

2023-09-02 01:16 UTC, BetzabeFI commented on guia-examen/05-dtl/05-dtl.md
> +junto con rollback permitiendo deshacer cambios hasta los `savepoint`.
Cambio realizado

2023-09-02 01:19 UTC, BetzabeFI commented on guia-examen/05-dtl/05-dtl.md
> +El número de `savepoint` esta limitado a 5 por sesión pero lo podemos modificar con la
Cambio realizado. Gracias

2023-09-02 01:27 UTC, BetzabeFI commented on guia-examen/05-dtl/05-dtl.md
> +* `rollback to`
Agregado to numero. Gracias

2023-09-02 01:31 UTC, BetzabeFI commented on guia-examen/05-dtl/05-dtl.md
> +Deshace el trabajo realizado después del punto indicado. Pero no se confirma el trabajo
Cambio realizado. Gracias

2023-09-02 01:36 UTC, BetzabeFI commented on guia-examen/05-dtl/05-dtl.md
> +create or replace procedure prueba (nfilas number)
Bloque anónimo realizado. Gracias

2023-09-02 01:37 UTC, BetzabeFI commented on guia-examen/05-dtl/05-dtl.md
> +Todas las transacciones de Oracle obedecen a las propiedades básicas de una transacción de
Quite Oracle. Gracias

2023-09-02 01:40 UTC, BetzabeFI commented on guia-examen/05-dtl/05-dtl.md
> +Oracle Database debe permitir dos situaciones. Si las tres sentencias SQL mantienen las
Cambio realizado

2023-09-02 01:56 UTC, BetzabeFI commented on guia-examen/05-dtl/img/5_2_figura_ACID.png
Si la hice

2023-09-02 21:22 UTC, jorgerdc requested changes

2023-09-02 21:22 UTC, jorgerdc commented on guia-examen/05-dtl/05-dtl.md
> +END;
Revisar el documento, homologar el còdigo a minùsculas.

2023-09-04 00:22 UTC, BetzabeFI commented on guia-examen/05-dtl/05-dtl.md
> +END;
homologado a minúsculas. Gracias

2023-09-04 02:11 UTC, jorgeacalderon approved these changes

2023-09-04 19:50 UTC, jorgerdc approved these changes

2023-09-04 19:54 UTC, LucilaArellano approved these changes

2023-09-07 02:16 UTC, merged